### ISSUE TITLE
Create Static Files

### ISSUE THREAD

**Issue by Janisroz** [Janisroz/SatoriKnowledgeBase#15]
As a **Developer** I must **create static file capability** so that **I can create and manage static files such as css and images**

**Acceptance Criteria**

- Create static folder in root directory
- Create CSS folder and styles.css file
- Link styles file to base.html

**Comment by Janisroz** [comment]
**Tasks**

- [ ] Create static folder in root directory

- [ ] Create CSS folder and styles.css file

- [ ] Link styles file to base.html
