### ISSUE TITLE
USER STORY- Open a Video

### ISSUE THREAD

**Issue by Janisroz** [Janisroz/SatoriKnowledgeBase#3]
As a Site User I can **Open a video ** so that can watch it and interact

**Comment by Janisroz** [comment]
### Tasks
- [x]  Create template for each individual post page displaying: video & comments
- [x] Create Views for this page
- [x] Add embedded video
- [x] Add Comment section
- [x] style page
